name: coverage-web

on:
  workflow_dispatch:
  push:
    branches: [ main, fix/web-export-import ]

jobs:
  collect-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
      - name: Install pdftotext (poppler-utils)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
      - name: Get packages
        run: flutter pub get
      - name: Run coverage script
        run: |
          chmod +x ./scripts/collect_coverage.sh
          ./scripts/collect_coverage.sh
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/html
